name: Construir y Publicar en Docker Hub

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Esto habilita un botón para ejecutarlo manualmente si quieres

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Login en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # --- BACKEND ---
      - name: Build y Push Backend
        uses: docker/build-push-action@v4
        with:
          # Contexto: Dónde está el código fuente del back
          context: ./backend
          # Archivo: Dónde está el Dockerfile del back
          file: ./contenedores_final_HIA/Dockerfile.backend
          push: true
          # Esto creará: maurotarifa/tpfinal_hia-backend:latest
          tags: ${{ secrets.DOCKER_USERNAME }}/tpfinal_hia-backend:latest

      # --- FRONTEND ---
      - name: Build y Push Frontend
        uses: docker/build-push-action@v4
        with:
          # Contexto: Dónde está el código fuente del front
          context: ./frontend
          # Archivo: Dónde está el Dockerfile del front
          file: ./contenedores_final_HIA/Dockerfile.frontend
          push: true
          # Esto creará: maurotarifa/tpfinal_hia-frontend:latest
          tags: ${{ secrets.DOCKER_USERNAME }}/tpfinal_hia-frontend:latest
