name: Construir y Publicar en Docker Hub

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      # ======================================================
      #  PREPARACIÓN DE ARCHIVOS (ESTRATEGIA TOTAL)
      # ======================================================
      - name: Mover Archivos de Soporte
        run: |
          echo "--- 1. Preparando BACKEND ---"
          # El error anterior decia: not found "scripts/carga_masiva.py"
          # Por eso copiamos la carpeta 'scripts' directo a la raiz del backend
          cp -r contenedores_final_HIA/scripts backend/
          cp -r contenedores_final_HIA/config backend/
          cp contenedores_final_HIA/entrypoint.sh backend/

          echo "--- 2. Preparando FRONTEND ---"
          # El error anterior decia: not found "contenedores_final_HIA/nginx.conf"
          # Por eso creamos esa carpeta ADENTRO del frontend y copiamos el archivo
          mkdir -p frontend/contenedores_final_HIA
          cp contenedores_final_HIA/nginx.conf frontend/contenedores_final_HIA/
          
          # Copiamos todo lo demas dentro de esa carpeta por seguridad
          cp -r contenedores_final_HIA/* frontend/contenedores_final_HIA/

      - name: Login en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # --- BACKEND ---
      - name: Build y Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./contenedores_final_HIA/Dockerfile.backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/tpfinal_hia-backend:latest

      # --- FRONTEND ---
      - name: Build y Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./contenedores_final_HIA/Dockerfile.frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/tpfinal_hia-frontend:latest
